### ISSUE TITLE
Convert to Remix

### ISSUE THREAD

**Issue by smokinjoe** [smokinjoe/advent-of-code-2023#14]

**Comment by smokinjoe** [comment]
## Todo

- [ ] add foundation
- [ ] import styles
- [ ] import navigation
- [ ] provide txt input data
- [ ] import DayForm
- [ ] import Days as routes with params

**Comment by smokinjoe** [comment]
## Additional features

- [ ] Store txt files in database?
- [ ] Provide a login of sorts?

**Comment by smokinjoe** [comment]
All done and merged back into `main`
